# GitHub Secret Scanning configuration
# Docs: https://docs.github.com/en/code-security/secret-scanning

# Paths to exclude from secret scanning (use sparingly)
# paths-ignore:
#   - "docs/examples/**"
#   - "**/*_test.go"

# Push protection is enabled by default for public repos
# Contributors will be blocked from pushing detected secrets
# They can bypass with a reason (false positive, used in tests, will fix later)
